name: run-tests
on:
  push:
    - main
  pull_request:
    branches:
      -main


jobs:
  tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup
        uses: actions/checkout@v4
      - name: setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '19'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Run tests
        run: mvn -B tests --file pom.xml


